//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessStructure.WPF.AService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/BS.AuthenticationService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestResultOfUserResultUserErrorjphcqKqy", Namespace="http://schemas.datacontract.org/2004/07/BS.AuthenticationService")]
    [System.SerializableAttribute()]
    public partial class RequestResultOfUserResultUserErrorjphcqKqy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BusinessStructure.WPF.AService.UserResult DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BusinessStructure.WPF.AService.UserError ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BusinessStructure.WPF.AService.UserResult Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BusinessStructure.WPF.AService.UserError Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResult", Namespace="http://schemas.datacontract.org/2004/07/BS.AuthenticationService")]
    [System.SerializableAttribute()]
    public partial class UserResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullUserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullUserName {
            get {
                return this.FullUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullUserNameField, value) != true)) {
                    this.FullUserNameField = value;
                    this.RaisePropertyChanged("FullUserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserError", Namespace="http://schemas.datacontract.org/2004/07/BS.AuthenticationService")]
    [System.SerializableAttribute()]
    public partial class UserError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BusinessStructure.WPF.AService.UserErrorEnum UserErrorEnumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageError {
            get {
                return this.MessageErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageErrorField, value) != true)) {
                    this.MessageErrorField = value;
                    this.RaisePropertyChanged("MessageError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BusinessStructure.WPF.AService.UserErrorEnum UserErrorEnum {
            get {
                return this.UserErrorEnumField;
            }
            set {
                if ((this.UserErrorEnumField.Equals(value) != true)) {
                    this.UserErrorEnumField = value;
                    this.RaisePropertyChanged("UserErrorEnum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserErrorEnum", Namespace="http://schemas.datacontract.org/2004/07/BS.AuthenticationService")]
    public enum UserErrorEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserLocked = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestResultOfUserInfoResultArrayOfUserInfoErrorEnumjphcqKqy", Namespace="http://schemas.datacontract.org/2004/07/BS.AuthenticationService")]
    [System.SerializableAttribute()]
    public partial class RequestResultOfUserInfoResultArrayOfUserInfoErrorEnumjphcqKqy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BusinessStructure.WPF.AService.UserInfoResult DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BusinessStructure.WPF.AService.UserInfoErrorEnum[] ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BusinessStructure.WPF.AService.UserInfoResult Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BusinessStructure.WPF.AService.UserInfoErrorEnum[] Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfoResult", Namespace="http://schemas.datacontract.org/2004/07/BS.AuthenticationService")]
    [System.SerializableAttribute()]
    public partial class UserInfoResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfoErrorEnum", Namespace="http://schemas.datacontract.org/2004/07/BS.AuthenticationService")]
    public enum UserInfoErrorEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Locked = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AService.IAuthentificationManagement")]
    public interface IAuthentificationManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/GetData", ReplyAction="http://tempuri.org/IAuthentificationManagement/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/GetData", ReplyAction="http://tempuri.org/IAuthentificationManagement/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAuthentificationManagement/GetDataUsingDataContractResponse")]
        BusinessStructure.WPF.AService.CompositeType GetDataUsingDataContract(BusinessStructure.WPF.AService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IAuthentificationManagement/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<BusinessStructure.WPF.AService.CompositeType> GetDataUsingDataContractAsync(BusinessStructure.WPF.AService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/Login", ReplyAction="http://tempuri.org/IAuthentificationManagement/LoginResponse")]
        BusinessStructure.WPF.AService.RequestResultOfUserResultUserErrorjphcqKqy Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/Login", ReplyAction="http://tempuri.org/IAuthentificationManagement/LoginResponse")]
        System.Threading.Tasks.Task<BusinessStructure.WPF.AService.RequestResultOfUserResultUserErrorjphcqKqy> LoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/GetUserInfo", ReplyAction="http://tempuri.org/IAuthentificationManagement/GetUserInfoResponse")]
        BusinessStructure.WPF.AService.RequestResultOfUserInfoResultArrayOfUserInfoErrorEnumjphcqKqy GetUserInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/GetUserInfo", ReplyAction="http://tempuri.org/IAuthentificationManagement/GetUserInfoResponse")]
        System.Threading.Tasks.Task<BusinessStructure.WPF.AService.RequestResultOfUserInfoResultArrayOfUserInfoErrorEnumjphcqKqy> GetUserInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/ResetPassword", ReplyAction="http://tempuri.org/IAuthentificationManagement/ResetPasswordResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessStructure.WPF.AService.CompositeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessStructure.WPF.AService.RequestResultOfUserResultUserErrorjphcqKqy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessStructure.WPF.AService.UserResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessStructure.WPF.AService.UserError))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessStructure.WPF.AService.UserErrorEnum))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessStructure.WPF.AService.RequestResultOfUserInfoResultArrayOfUserInfoErrorEnumjphcqKqy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessStructure.WPF.AService.UserInfoResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessStructure.WPF.AService.UserInfoErrorEnum[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BusinessStructure.WPF.AService.UserInfoErrorEnum))]
        object ResetPassword(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthentificationManagement/ResetPassword", ReplyAction="http://tempuri.org/IAuthentificationManagement/ResetPasswordResponse")]
        System.Threading.Tasks.Task<object> ResetPasswordAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthentificationManagementChannel : BusinessStructure.WPF.AService.IAuthentificationManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthentificationManagementClient : System.ServiceModel.ClientBase<BusinessStructure.WPF.AService.IAuthentificationManagement>, BusinessStructure.WPF.AService.IAuthentificationManagement {
        
        public AuthentificationManagementClient() {
        }
        
        public AuthentificationManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthentificationManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthentificationManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthentificationManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public BusinessStructure.WPF.AService.CompositeType GetDataUsingDataContract(BusinessStructure.WPF.AService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<BusinessStructure.WPF.AService.CompositeType> GetDataUsingDataContractAsync(BusinessStructure.WPF.AService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public BusinessStructure.WPF.AService.RequestResultOfUserResultUserErrorjphcqKqy Login(string login1, string password) {
            return base.Channel.Login(login1, password);
        }
        
        public System.Threading.Tasks.Task<BusinessStructure.WPF.AService.RequestResultOfUserResultUserErrorjphcqKqy> LoginAsync(string login, string password) {
            return base.Channel.LoginAsync(login, password);
        }
        
        public BusinessStructure.WPF.AService.RequestResultOfUserInfoResultArrayOfUserInfoErrorEnumjphcqKqy GetUserInfo() {
            return base.Channel.GetUserInfo();
        }
        
        public System.Threading.Tasks.Task<BusinessStructure.WPF.AService.RequestResultOfUserInfoResultArrayOfUserInfoErrorEnumjphcqKqy> GetUserInfoAsync() {
            return base.Channel.GetUserInfoAsync();
        }
        
        public object ResetPassword(string email) {
            return base.Channel.ResetPassword(email);
        }
        
        public System.Threading.Tasks.Task<object> ResetPasswordAsync(string email) {
            return base.Channel.ResetPasswordAsync(email);
        }
    }
}
